.TH JALV.SELECT 1 "January 17, 2017"
.SH NAME
jalv.select \- GUI for selecting lv2 plugins
.SH SYNOPSIS
.B jalv.select
.RI [OPTION...]
.SH DESCRIPTION
jalv.select is a little gtkmm GUI to select lv2 plugs from a list and run them with jalv.
.PP
.SH OPTIONS
This program follows the usual GNU command line syntax, with long
options starting with two dashes (`\-').
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-s, \-\-systray
Start minimized in systray.
.TP
.B \-H, \-\-high=HIGH
Set the initial window high in pixel.
.SH AUTHOR
jalv.select was written by Hermann Meyer <brummer-@web.de>.
.PP
Send comments, bug reports and patches to jalv.select forge at
https:\/\/github.com\/brummer10\/jalv_select\/
.PP
This manual page was written by Olivier Humbert <trebmuh@tuxfamily.org>,
for the LibraZiK project (but may be used by others).
