.TH JALV.SELECT 1 "Janvier 17, 2017"
.SH NOM
jalv.select \- interface graphique pour sélectionner des greffons LV2
.SH SYNOPSIS
.B jalv.select
.RI [OPTION...]
.SH DESCRIPTION
jalv.select est une petite interface graphique gtkmm pour sélectionner des
greffons LV2 à partir d'une liste, et les lancer avec jalv.
.PP
.SH OPTIONS
Ce programme suit la syntaxe en ligne de commande GNU habituelle, avec les
options longues commençant avec deux tirets (`\-').
Un sommaire des options est inclus ci-dessous.
.TP
.B \-h, \-\-help
Affiche un sommaire des options.
.TP
.B \-s, \-\-systray
Démarre minimisé dans la barre des tâches.
.TP
.B \-H, \-\-high=HAUTEUR
Paramètre la hauteur initiale de la fenêtre en pixel.
.SH AUTEUR
jalv.select a été écrit par Hermann Meyer <brummer-@web.de>.
.PP
Envoyez des commentaires, des rapports de bogues, et des patches sur la forge de
jalv.select à https:\/\/github.com\/brummer10\/jalv_select\/
.PP
Cette page de manuel ainsi que la traduction française ont été écrites par
Olivier Humbert <trebmuh@tuxfamily.org>, pour le projet LibraZiK (mais peuvent
être utilisées par d'autres).
